[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "system-sl"
version = "0.1.0"
description = "A CLI-based Solo Leveling-inspired task management system."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
  "plyer",
  "google-api-python-client",
  "google-auth-httplib2",
  "google-auth-oauthlib",
]

[tool.setuptools.packages]
find = {where = ["src"]}